// Virtual modules generated by vite/plugins/blog-plugin.ts.
declare module "virtual:blog-index" {
  export type PostMeta = {
    title: string;
    slug: string;
    description: string;
    date: string;
    updated: string;
    author: string;
    category: string;
    tags: string[];
    image: string;
    imageAlt: string;
    legacyUrl?: string;
    words: number;
    readingMinutes: number;
    headings: { id: string; text: string }[];
  };
  export const posts: PostMeta[];
  export const bodyLoaders: Record<string, () => Promise<string>>;
}
declare module "virtual:blog-bodies" {
  const bodies: Record<string, string>;
  export default bodies;
}
