/**
 * Live-trip overlay geometry — measured from the site's real app recordings.
 *
 * Each entry describes one video in `public/media/` (pixel coordinates of that
 * video): the customer map, the baked route polyline, the van marker and the
 * ETA texts on the arrival page. `patch` is an RGBA image that erases the
 * baked route / van / ETA texts so <LiveTripOverlay> can draw them live.
 * Generated by the asset pipeline (scratch/geo/analyze.py + emit.py) on 2026-10-07.
 */
export type LiveTripGeometry = {
  id: string;
  size: [number, number];
  /** "clock": the trip runs on wall-clock time while the slot plays. "video": positions follow video.currentTime (one-shot clips). */
  mode: "clock" | "video";
  /** Opacity ramps tied to the base video's own fades: [fromSec, toSec, fromOpacity, toOpacity]. */
  fades: [number, number, number, number][];
  patch: { src: string; rect: [number, number, number, number] };
  map: [number, number, number, number];
  route: [number, number][];
  routeWidth: number;
  routeColor: string;
  van: { src: string; r: number };
  bubble: { dx: number; dy: number; w: number; h: number; bg: string; fs: number };
  big: { x: number; baseline: number; fs: number };
  time: { right: number; baseline: number; fs: number };
  km: { right: number; baseline: number; fs: number; color: string };
};

export const liveTripGeometry: LiveTripGeometry[] = [
  {"id": "arrival-16x10", "size": [1600, 1000], "mode": "clock", "fades": [], "patch": {"src": "/media/live/arrival-16x10-patch.webp", "rect": [1129, 253, 351, 384]}, "map": [1125, 181, 361, 371], "route": [[1199.5, 512.5], [1217.0, 466.0], [1215.0, 456.0], [1219.0, 396.0], [1221.0, 394.0], [1383.0, 403.0], [1399.0, 402.0], [1406.0, 259.0], [1410.5, 256]], "routeWidth": 4.01, "routeColor": "#149bd6", "van": {"src": "/media/live/arrival-16x10-van.webp", "r": 15}, "bubble": {"dx": -0.5, "dy": -44.5, "w": 46, "h": 24, "bg": "#0b1222", "fs": 11.04}, "big": {"x": 1140.7, "baseline": 628, "fs": 33.01}, "time": {"right": 1469, "baseline": 597, "fs": 12.38}, "km": {"right": 1470, "baseline": 613.2, "fs": 12.38, "color": "#b3b8c7"}},
  {"id": "arrival-3x4", "size": [1080, 1440], "mode": "clock", "fades": [], "patch": {"src": "/media/live/arrival-3x4-patch.webp", "rect": [408, 189, 262, 283]}, "map": [409, 139, 263, 269], "route": [[462.5, 378.5], [475.0, 342.0], [478.0, 293.0], [585.0, 299.0], [609.0, 298.0], [614.0, 196.0], [618.0, 192]], "routeWidth": 4.01, "routeColor": "#1d9ad3", "van": {"src": "/media/live/arrival-3x4-van.webp", "r": 12}, "bubble": {"dx": 0.5, "dy": -31.5, "w": 34, "h": 18, "bg": "#0c121f", "fs": 8.28}, "big": {"x": 420.1, "baseline": 463, "fs": 23.38}, "time": {"right": 660, "baseline": 441, "fs": 8.25}, "km": {"right": 659, "baseline": 452.1, "fs": 8.25, "color": "#acb4c0"}},
  {"id": "comms-16x10", "size": [1600, 1000], "mode": "clock", "fades": [], "patch": {"src": "/media/live/comms-16x10-patch.webp", "rect": [871, 253, 351, 383]}, "map": [867, 181, 361, 371], "route": [[940.5, 511.5], [959.0, 466.0], [957.0, 458.0], [961.0, 396.0], [963.0, 394.0], [1126.0, 403.0], [1141.0, 402.0], [1148.0, 259.0], [1152.5, 256]], "routeWidth": 4.01, "routeColor": "#149bd7", "van": {"src": "/media/live/comms-16x10-van.webp", "r": 15}, "bubble": {"dx": 1.0, "dy": -43.5, "w": 47, "h": 23, "bg": "#0a121e", "fs": 10.58}, "big": {"x": 882.7, "baseline": 627, "fs": 31.64}, "time": {"right": 1211, "baseline": 597, "fs": 12.38}, "km": {"right": 1212, "baseline": 613.2, "fs": 12.38, "color": "#b8bfcd"}},
  {"id": "comms-3x4", "size": [1080, 1440], "mode": "clock", "fades": [], "patch": {"src": "/media/live/comms-3x4-patch.webp", "rect": [601, 473, 352, 384]}, "map": [597, 400, 362, 372], "route": [[670.5, 730.5], [688.0, 684.0], [691.0, 616.0], [694.0, 613.0], [872.0, 622.0], [879.0, 502.0], [878.0, 479.0], [884.0, 476]], "routeWidth": 4.01, "routeColor": "#159dd7", "van": {"src": "/media/live/comms-3x4-van.webp", "r": 15}, "bubble": {"dx": 1.0, "dy": -42.5, "w": 47, "h": 23, "bg": "#0b1321", "fs": 10.58}, "big": {"x": 612.7, "baseline": 848, "fs": 33.01}, "time": {"right": 942, "baseline": 817, "fs": 12.38}, "km": {"right": 943, "baseline": 833.2, "fs": 12.38, "color": "#b1b9c6"}},
  {"id": "tracking-4x3", "size": [1440, 1080], "mode": "clock", "fades": [[0.0, 0.5, 0, 1]], "patch": {"src": "/media/live/tracking-4x3-patch.webp", "rect": [527, 269, 384, 421]}, "map": [521, 190, 399, 407], "route": [[602.5, 553.5], [621.0, 502.0], [625.0, 425.0], [627.0, 423.0], [802.0, 433.0], [825.0, 432.0], [832.0, 276.0], [837.0, 272]], "routeWidth": 6.02, "routeColor": "#119cda", "van": {"src": "/media/live/tracking-4x3-van.webp", "r": 17}, "bubble": {"dx": 0.5, "dy": -48.5, "w": 52, "h": 27, "bg": "#0b1220", "fs": 12.42}, "big": {"x": 538.6, "baseline": 681, "fs": 35.76}, "time": {"right": 901, "baseline": 647, "fs": 13.76}, "km": {"right": 901, "baseline": 664.2, "fs": 13.76, "color": "#adb4c2"}},
  {"id": "closing-16x10", "size": [1600, 1000], "mode": "video", "fades": [[0.0, 0.5, 0, 1], [2.7, 3.0, 1, 0]], "patch": {"src": "/media/live/closing-16x10-patch.webp", "rect": [624, 255, 349, 381]}, "map": [620, 182, 360, 369], "route": [[692.5, 511.5], [711.0, 463.0], [714.0, 394.0], [866.0, 401.0], [872.0, 403.0], [894.0, 402.0], [901.0, 260.0], [905.5, 257]], "routeWidth": 4.01, "routeColor": "#189ad4", "van": {"src": "/media/live/closing-16x10-van.webp", "r": 16}, "bubble": {"dx": 1.0, "dy": -43.5, "w": 47, "h": 24, "bg": "#0b1727", "fs": 11.04}, "big": {"x": 635.7, "baseline": 627, "fs": 31.64}, "time": {"right": 963, "baseline": 596, "fs": 11.0}, "km": {"right": 962, "baseline": 614.1, "fs": 11.0, "color": "#bec4d3"}},
];

export function liveTrip(id: string | undefined): LiveTripGeometry | undefined {
  return id ? liveTripGeometry.find((g) => g.id === id) : undefined;
}
