#!/usr/bin/env python3
"""Regenerate src/web/lib/basemap/arriveping-ink.style.json.

Pulls OpenFreeMap's "dark" MapLibre style and recolours it to the ArrivePing
palette (ink #070b12 background, cyan-leaning highways, blue-black water).
The result is vendored into the repo so a change upstream can't silently
restyle the product; rerun this script when you want to pick up new layers.

    python3 packages/web/tools/gen-ink-style.py
"""
import json
import pathlib
import urllib.request

SRC = "https://tiles.openfreemap.org/styles/dark"
OUT = pathlib.Path(__file__).resolve().parents[1] / "src/web/lib/basemap/arriveping-ink.style.json"

INK = "#070b12"

# layer id -> paint overrides (ids are OpenFreeMap's; see the style for the full list)
PAINT = {
    "background": {"background-color": INK},
    "water": {"fill-color": "#0d2238"},
    "waterway": {"line-color": "#123049"},
    "water_name": {"text-color": "#3d6a8a", "text-halo-color": INK},
    "landuse_residential": {"fill-color": "#0b111b"},
    "landcover_wood": {"fill-color": "#0b1711"},
    "landuse_park": {"fill-color": "#0c1a14"},
    "landcover_ice_shelf": {"fill-color": INK},
    "landcover_glacier": {"fill-color": INK},
    "building": {"fill-color": "#121a2b", "fill-outline-color": "#1c2742"},
    "aeroway-area": {"fill-color": "#0b1220"},
    "aeroway-runway": {"line-color": "#0b1220"},
    "aeroway-runway-casing": {"line-color": "#1b2a40"},
    "aeroway-taxiway": {"line-color": "#15213a"},
    "road_area_pier": {"fill-color": INK},
    "road_pier": {"line-color": INK},
    "highway_path": {"line-color": "#131c2a"},
    "highway_minor": {"line-color": "#1b2638"},
    "highway_major_casing": {"line-color": "#0d1626"},
    "highway_major_inner": {"line-color": "#334a66"},
    "highway_major_subtle": {"line-color": "#2a3b52"},
    "highway_motorway_casing": {"line-color": "#0a2435"},
    "highway_motorway_inner": {"line-color": "#1a6f98"},
    "highway_motorway_subtle": {"line-color": "#164a66"},
    "railway": {"line-color": "#1c2738"},
    "railway_dashline": {"line-color": INK},
    "railway_minor": {"line-color": "#1c2738"},
    "railway_minor_dashline": {"line-color": INK},
    "railway_transit": {"line-color": "#1c2738"},
    "railway_transit_dashline": {"line-color": INK},
    "highway_name_other": {"text-color": "#6b82a0", "text-halo-color": INK},
    "highway_name_motorway": {"text-color": "#5aa7cf"},
    "boundary_state": {"line-color": "#23364d"},
    "boundary_country_z0-4": {"line-color": "#2a4059"},
    "boundary_country_z5-": {"line-color": "#2a4059"},
}


def main() -> None:
    req = urllib.request.Request(SRC, headers={"User-Agent": "ArrivePing style generator (arriveping.com)"})
    with urllib.request.urlopen(req) as r:
        style = json.load(r)

    ids = {layer["id"] for layer in style["layers"]}
    missing = [k for k in PAINT if k not in ids]
    if missing:
        print("WARNING: upstream no longer has layers:", ", ".join(missing))

    for layer in style["layers"]:
        paint = layer.setdefault("paint", {})
        if layer["id"] in PAINT:
            paint.update(PAINT[layer["id"]])
        if layer["id"].startswith("place_"):
            paint.update({"text-color": "#aebccf", "text-halo-color": INK, "text-halo-width": 1.4})

    style["name"] = "ArrivePing Ink"
    style["metadata"] = {
        "arriveping:source": SRC,
        "arriveping:note": "Generated by packages/web/tools/gen-ink-style.py — edit that script, not this file.",
    }
    OUT.write_text(json.dumps(style, indent=1) + "\n")
    print(f"wrote {OUT} ({len(style['layers'])} layers)")


if __name__ == "__main__":
    main()
